using BBDownT.Core.Protobuf;
using Google.Protobuf;
using System.Text;
using static BBDownT.Core.Entity.Entity;
using static BBDownT.Core.Util.HTTPUtil;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.IO;
using static BBDownT.Core.Logger;

namespace BBDownT.Core.Util;

public static partial class SubUtil
{
    internal static bool HaveValidUrls(IEnumerable<Subtitle> subtitles)
    {
        return subtitles.All(subtitle => !string.IsNullOrEmpty(subtitle.url));
    }

    //https://i0.hdslb.com/bfs/subtitle/subtitle_lan.json
    public static (string, string) GetSubtitleCode(string key)
    {
        //zh-hans => zh-Hans
        if (NonCapsRegex().Match(key) is { Success: true } result)
        {
            var v = result.Value;
            key = key.Replace(v, v.ToUpper());
        }

        return key switch
        {
            "ai-Zh"             => ("chi", "中文（简体, AI识别）"),
            "ai-En"             => ("eng", "English(generated by ai)"),
            "zh"                => ("chi", "中文"),
            "zh-CN"             => ("chi", "中文（简体）"),
            "zh-HK"             => ("chi", "中文（香港繁體）"),
            "zh-Hans"           => ("chi", "中文（简体）"),
            "zh-TW"             => ("chi", "中文（台灣繁體）"),
            "zh-Hant"           => ("chi", "中文（繁體）"),
            "en-US"             => ("eng", "English(USA)"),
            "ja"                => ("jpn", "日本語"),
            "ko"                => ("kor", "한국어"),
            "zh-SG"             => ("chi", "中文（新加坡）"),
            "ab"                => ("abk", "Аҳәынҭқарра"),
            "aa"                => ("aar", "Qafár af"),
            "af"                => ("afr", "Afrikaans"),
            "sq"                => ("alb", "Gjuha shqipe"),
            "ase"               => ("ase", "American Sign Language"),
            "am"                => ("amh", "አማርኛ"),
            "ar"                => ("ara", "العربية"),
            "arc"               => ("arc", "ܐܪܡܝܐ"),
            "hy"                => ("arm", "հայերեն"),
            "as"                => ("asm", "অসমীয়া"),
            "ay"                => ("aym", "Aymar aru"),
            "az"                => ("aze", "Azərbaycan"),
            "bn"                => ("ben", "বাংলা ভাষার"),
            "ba"                => ("bak", "Башҡорттеле"),
            "eu"                => ("baq", "Euskara"),
            "be"                => ("bel", "беларуская мова biełaruskaja mova"),
            "bh"                => ("bih", "Bihar"),
            "bi"                => ("bis", "Bislama"),
            "bs"                => ("bos", "босански"),
            "br"                => ("bre", "Breton"),
            "bg"                => ("bul", "български"),
            "yue"               => ("chi", "粵語"),
            "yue-HK"            => ("chi", "粵語（中國香港）"),
            "ca"                => ("cat", "català"),
            "chr"               => ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"),
            "cho"               => ("cho", "Chahta'"),
            "co"                => ("cos", "lingua corsa"),
            "hr"                => ("hrv", "Hrvatska"),
            "cs"                => ("cze", "čeština"),
            "da"                => ("dan", "Dansk"),
            "nl"                => ("dut", "Nederlands"),
            "nl-BE"             => ("dut", "Nederlands(Belgisch)"),
            "nl-NL"             => ("dut", "Nederlands(Nederlands)"),
            "dz"                => ("dzo", "རྫོང་ཁ།"),
            "en"                => ("eng", "English"),
            "en-CA"             => ("eng", "English(Canada)"),
            "en-IE"             => ("eng", "English(Ireland)"),
            "en-GB"             => ("eng", "English(UK)"),
            "eo"                => ("epo", "Esperanto"),
            "et"                => ("est", "Eestlane"),
            "fo"                => ("fao", "føroyskt"),
            "fj"                => ("fij", "Vakaviti"),
            "fil"               => ("phi", "Pilipino"),
            "fi"                => ("fin", "Suomi"),
            "fr"                => ("fre", "Français"),
            "fr-BE"             => ("fre", "Français(Belgique)"),
            "fr-CA"             => ("fre", "Français(Canada)"),
            "fr-FR"             => ("fre", "Français(La France)"),
            "fr-CH"             => ("fre", "Français(Suisse)"),
            "ff"                => ("ful", "Fulani"),
            "gl"                => ("glg", "galego"),
            "ka"                => ("geo", "ქართული ენა"),
            "de"                => ("ger", "Deutsch"),
            "de-AT"             => ("ger", "Deutsch(Österreich)"),
            "de-DE"             => ("ger", "Deutsch(Deutschland)"),
            "de-CH"             => ("ger", "Deutsch(Schweiz)"),
            "el"                => ("gre", "Ελληνικά"),
            "kl"                => ("kal", "Kalaallisut"),
            "gn"                => ("grn", "avañe'ẽ"),
            "gu"                => ("guj", "ગુજરાતી"),
            "hak"               => ("hak", "Hak-kâ-fa"),
            "hak-TW"            => ("hak", "Hak-kâ-fa"),
            "ha"                => ("hau", "هَوُسَ"),
            "iw"                => ("heb", "שפה עברית"),
            "hi"                => ("hin", "हिन्दी"),
            "hi-Latn"           => ("hin", "हिंदी(फोनेटिक)"),
            "hu"                => ("hun", "Magyar"),
            "is"                => ("ice", "icelandic"),
            "ig"                => ("ibo", "Asụsụ Igbo"),
            "id"                => ("ind", "Indonesia"),
            "ia"                => ("ina", "Interlingua"),
            "iu"                => ("iku", "ᐃᓄᒃᑎᑐᑦ"),
            "ik"                => ("ipk", "Inupiat"),
            "ga"                => ("gle", "Gaeilge na hÉireann"),
            "it"                => ("ita", "Italiano"),
            "jv"                => ("jav", "ꦧꦱꦗꦮ"),
            "kn"                => ("kan", "ಕನ್ನಡ"),
            "ks"                => ("kas", "कॉशुर"),
            "kk"                => ("kaz", "Қазақ тілі"),
            "km"                => ("khm", "ភាសាខ្មែរ"),
            "rw"                => ("kin", "Ikinyarwanda"),
            "tlh"               => ("tlh", "tlhIngan Hol"),
            "ku"                => ("kur", "Kurdî"),
            "ky"                => ("kir", "кыргыз тили"),
            "lo"                => ("lao", "ພາສາລາວ"),
            "la"                => ("lat", "latīna"),
            "lv"                => ("lav", "latviešu valoda"),
            "ln"                => ("lin", "Lingála"),
            "lt"                => ("lit", "lietuvių kalba"),
            "lb"                => ("ltz", "Lëtzebuergesch"),
            "mk"                => ("mac", "Македонски јазик"),
            "mg"                => ("mlg", "maa.laa.gaas"),
            "ms"                => ("may", "Melayu"),
            "ml"                => ("mal", "മലയാളം"),
            "mt"                => ("mlt", "Lingwa Maltija"),
            "mi"                => ("mao", "Māori"),
            "mr"                => ("mar", "मराठी Marāṭhī"),
            "mas"               => ("mas", "Maasai"),
            "nan"               => ("nan", "閩南語"),
            "nan-TW"            => ("nan", "閩南語(台灣)"),
            "lus"               => ("lus", "Mizo ṭawng"),
            "mo"                => ("mol", "Limba moldovenească"),
            "mn"                => ("mon", "монгол хэл"),
            "my"                => ("bur", "မြန်မာဘာသာ"),
            "na"                => ("nau", "Dorerin Naoero"),
            "nv"                => ("nav", "Diné bizaad"),
            "ne"                => ("nep", "नेपाली Nepālī"),
            "no"                => ("nor", "norsk språk"),
            "fa"                => ("per", "فارسی"),
            "fa-AF"             => ("per", "فارسی"),
            "fa-IR"             => ("per", "فارسی"),
            "pl"                => ("pol", "Polski"),
            "pt"                => ("por", "Português"),
            "pt-BR"             => ("por", "Português(brasil)"),
            "pt-PT"             => ("por", "Português(portugal)"),
            "ro"                => ("rum", "Română"),
            "ru"                => ("rus", "Русский"),
            "ru-Latn"           => ("rus", "Русский(фонетический)"),
            "sr"                => ("srp", "Српски"),
            "sr-Cyrl"           => ("srp", "Српски(ћирилица)"),
            "sr-Latn"           => ("srp", "Српски(латиница)"),
            "sh"                => ("scr", "srpskohrvatski"),
            "sk"                => ("slo", "slovenský"),
            "es"                => ("spa", "Español"),
            "es-419"            => ("spa", "Español(Latinoamérica)"),
            "es-MX"             => ("spa", "Español(México)"),
            "es-ES"             => ("spa", "Español(España)"),
            "es-US"             => ("spa", "Español(Estados Unidos)"),
            "sv"                => ("swe", "Svenska"),
            "tl"                => ("tgl", "Tagalog"),
            "th"                => ("tha", "ไทย"),
            "tr"                => ("tur", "Türkçe"),
            "uk"                => ("ukr", "Українська"),
            "ur"                => ("urd", "Urdu"),
            "vi"                => ("vie", "Tiếng Việt"),
            //太多了，我蚌埠住了，后面懒得查
            //"ie"                => ("", ""),
            //"oc"                => ("",   ""),
            //"or"                => ("",   ""),
            //"om"                => ("",   ""),
            //"ps"                => ("",   ""),
            //"pa"                => ("",   ""),
            //"qu"                => ("",   ""),
            //"rm"                => ("",   ""),
            //"rn"                => ("",   ""),
            //"sm"                => ("",   ""),
            //"sg"                => ("",   ""),
            //"sa"                => ("",   ""),
            //"gd"                => ("",   ""),
            //"sdp"               => ("",   ""),
            //"sn"                => ("",   ""),
            //"scn"               => ("",   ""),
            //"sd"                => ("",   ""),
            //"si"                => ("",   ""),
            //"sl"                => ("",   ""),
            //"so"                => ("",   ""),
            //"st"                => ("",   ""),
            //"su"                => ("",   ""),
            //"sw"                => ("",   ""),
            //"ss"                => ("",   ""),
            //"tg"                => ("",   ""),
            //"ta"                => ("",   ""),
            //"tt"                => ("",   ""),
            //"te"                => ("",   ""),
            //"ti"                => ("",   ""),
            //"to"                => ("",   ""),
            //"ts"                => ("",   ""),
            //"tn"                => ("",   ""),
            //"tk"                => ("",   ""),
            //"tw"                => ("",   ""),
            //"uz"                => ("",   ""),
            //"vo"                => ("",   ""),
            //"cy"                => ("",   ""),
            //"fy"                => ("",   ""),
            //"wo"                => ("",   ""),
            //"xh"                => ("",   ""),
            //"yi"                => ("",   ""),
            //"yo"                => ("",   ""),
            //"zu"                => ("",   ""),
            _ => ("und", "Undetermined")
        };
    }

    #region 字幕接口

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi1Async(string aid, string cid, string epId, int index, Func<string, Task<string>> fetch)
    {
        try
        {
            string api = "https://" + (Config.EPHOST == "api.bilibili.com" ? "api.bilibili.tv" : Config.EPHOST) + $"/intl/gateway/web/v2/subtitle?episode_id={epId}&platform=web&s_locale=en_US";
            string json = await fetch(api);
            return ParseIntlSubtitleResponse(json);
        }
        catch (Exception ex) when (ex is not IntlApiException)
        {
            LogDebug("国际字幕接口1失败: {0}", ex.Message);
            return null;
        }
    }

    internal static List<Subtitle> ParseIntlSubtitleResponse(string json)
    {
        using var document = JsonDocument.Parse(json);
        IntlBangumiWebApi.EnsureSuccess(document.RootElement);
        var data = document.RootElement.GetProperty("data");
        List<Subtitle> subtitles = [];
        foreach (var collection in new[] { "subtitles", "video_subtitle" })
        {
            if (!data.TryGetProperty(collection, out var entries) || entries.ValueKind != JsonValueKind.Array) continue;
            foreach (var entry in entries.EnumerateArray())
            {
                if (!entry.TryGetProperty("lang_key", out var language)) continue;
                var urls = new List<string>();
                if (entry.TryGetProperty("url", out var direct) && direct.ValueKind == JsonValueKind.String)
                    urls.Add(direct.GetString()!);
                foreach (var format in new[] { "ass", "srt" })
                {
                    if (entry.TryGetProperty(format, out var track) && track.ValueKind == JsonValueKind.Object
                        && track.TryGetProperty("url", out var url) && url.ValueKind == JsonValueKind.String)
                        urls.Add(url.GetString()!);
                }
                var usableUrls = urls.Where(url => !string.IsNullOrWhiteSpace(url)).ToList();
                // The shared ASS URL links the legacy list to video_subtitle's
                // ASS/JSON variants without collapsing independent same-language tracks.
                var anchor = usableUrls.FirstOrDefault(url => url.Split('?', '#')[0]
                    .EndsWith(".ass", StringComparison.OrdinalIgnoreCase)) ?? usableUrls.FirstOrDefault();
                var group = anchor is null ? null : "intl:" + NormalizeIntlVariantAnchor(anchor);
                foreach (var url in usableUrls)
                {
                    subtitles.Add(new Subtitle
                    {
                        lan = language.ToString(),
                        lanDoc = entry.TryGetProperty("lang", out var description) ? description.ToString() : null,
                        id = collection == "subtitles" && url == usableUrls[0] && entry.TryGetProperty("subtitle_id", out var id)
                            && id.ValueKind != JsonValueKind.Null ? id.ToString() : null,
                        url = url,
                        path = url.Split('?', '#')[0].EndsWith(".ass", StringComparison.OrdinalIgnoreCase) ? "subtitle.ass" : "subtitle.srt",
                        FormatVariantGroup = group
                    });
                }
            }
        }
        return subtitles;
    }

    private static string NormalizeIntlVariantAnchor(string url)
    {
        try { return NormalizeSubtitleUrl(url); }
        catch (FormatException) { return url; } // The existing merge path rejects unusable URLs.
    }

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi2Async(string aid, string cid, string epId, int index, Func<string, Task<string>> fetch)
    {
        try
        {
            List<Subtitle> subtitles = new();
            string api = "https://" + (Config.HOST == "api.bilibili.com" ? "api.bilibili.tv" : Config.HOST) +
                         $"/intl/gateway/v2/ogv/view/app/season?ep_id={epId}&platform=android&s_locale=zh_SG" + (Config.TOKEN != "" ? $"&access_key={Config.TOKEN}" : "");
            string json = await fetch(api);
            using var infoJson = JsonDocument.Parse(json);
            IntlBangumiWebApi.EnsureSuccess(infoJson.RootElement);
            var subs = infoJson.RootElement.GetProperty("result").GetProperty("modules")[0].GetProperty("data")
                .GetProperty("episodes")[index - 1].GetProperty("subtitles").EnumerateArray();
            foreach (var sub in subs)
            {
                var lan = sub.GetProperty("key").ToString();
                var url = sub.GetProperty("url").ToString().Replace("\\\\/", "/");
                Subtitle subtitle = new()
                {
                    url = url,
                    lan = lan,
                    path = $"{PathSegmentSanitizer.Sanitize(aid)}/{PathSegmentSanitizer.Sanitize(aid)}.{PathSegmentSanitizer.Sanitize(cid)}.{PathSegmentSanitizer.Sanitize(lan)}{(url.Contains(".json") ? ".srt" : ".ass")}"
                };

                subtitles.Add(subtitle);

            }
            return subtitles;
        }
        catch (Exception ex) when (ex is not IntlApiException)
        {
            LogDebug("国际字幕接口2失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromWebApiAsync(string aid, string cid, HttpClient client)
    {
        string contextExt = Uri.EscapeDataString("{\"video_type\":1}");
        string api = $"https://api.bilibili.com/x/v2/subtitle/web/view?oid={Uri.EscapeDataString(cid)}&pid={Uri.EscapeDataString(aid)}" +
                     $"&context_ext={contextExt}&type=1&cur_production_type=0&preferred_language=ai-zh&playlist_switch=0";
        try
        {
            using var request = new HttpRequestMessage(HttpMethod.Get, api);
            ApplyWebRequestHeaders(request, api);
            request.Headers.TryAddWithoutValidation("Accept", "application/octet-stream");
            using var response = (await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead)).EnsureSuccessStatusCode();
            return ParseSubtitleWebResponse(await response.Content.ReadAsByteArrayAsync());
        }
        catch (Exception ex)
        {
            LogDebug("新版字幕接口失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<string> GetSubtitleWebTextAsync(string api)
    {
        using var request = new HttpRequestMessage(HttpMethod.Get, api);
        ApplyWebRequestHeaders(request, api);
        request.Headers.TryAddWithoutValidation("Accept", "application/json");
        var client = !Config.COOKIE_IS_INTL ? AppHttpClient
            : ShouldSendCookie(api) ? GetWebHttpClient(true) : GetMediaHttpClient(true);
        using var response = (await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead)).EnsureSuccessStatusCode();
        return await response.Content.ReadAsStringAsync();
    }

    internal static List<Subtitle> ParseSubtitleWebResponse(ReadOnlySpan<byte> payload)
    {
        var reply = new MessageParser<SubtitleWebReply>(() => new SubtitleWebReply()).ParseFrom(payload.ToArray());
        return MapProtoSubtitles(reply.Subtitle);
    }

    internal static List<Subtitle> MergeSubtitleSources(IEnumerable<IEnumerable<Subtitle>?> sources, string aid, string cid)
    {
        var result = new List<Subtitle>();
        var seenIds = new HashSet<string>(StringComparer.Ordinal);
        var seenUrls = new HashSet<string>(StringComparer.Ordinal);
        foreach (var source in sources)
        {
            if (source == null)
                continue;
            foreach (var subtitle in source)
            {
                try
                {
                    subtitle.url = NormalizeSubtitleUrl(subtitle.url);
                }
                catch (FormatException ex)
                {
                    LogWarn($"字幕 {subtitle.lan} 的下载地址无法解析：{ex.Message}");
                    continue;
                }
                if (!IsUsableSubtitle(subtitle))
                    continue;
                bool duplicateId = !string.IsNullOrEmpty(subtitle.id) && seenIds.Contains(subtitle.id);
                bool duplicateUrl = seenUrls.Contains(subtitle.url);
                if (duplicateId || duplicateUrl)
                {
                    continue;
                }
                if (!string.IsNullOrEmpty(subtitle.id))
                    seenIds.Add(subtitle.id);
                seenUrls.Add(subtitle.url);
                result.Add(subtitle);
            }
        }
        AssignSubtitlePaths(result, aid, cid);
        return result;
    }

    private static List<Subtitle> MapProtoSubtitles(VideoSubtitle? videoSubtitle)
    {
        if (videoSubtitle == null)
            return [];
        return videoSubtitle.Subtitles.Select(item => new Subtitle
        {
            id = item.HasId ? item.Id.ToString() : (item.HasIdStr ? item.IdStr : null),
            lan = item.Lan,
            lanDoc = item.HasLanDoc ? item.LanDoc : (item.HasLanDocBrief ? item.LanDocBrief : null),
            type = item.Type,
            aiType = item.HasAiType ? item.AiType : null,
            url = item.SubtitleUrl,
            path = ""
        }).ToList();
    }

    private static string NormalizeSubtitleUrl(string url)
    {
        return SubtitleUrlResolver.Normalize(url);
    }

    private static bool HasUsableSubtitle(IEnumerable<Subtitle>? subtitles)
    {
        return subtitles?.Any(IsUsableSubtitle) == true;
    }

    private static bool IsUsableSubtitle(Subtitle subtitle) => !string.IsNullOrWhiteSpace(subtitle.lan)
        && Uri.TryCreate(NormalizeSubtitleUrl(subtitle.url), UriKind.Absolute, out var uri)
        && uri.Scheme is "http" or "https";

    private static void AssignSubtitlePaths(IList<Subtitle> subtitles, string aid, string cid)
    {
        string prefix = $"{PathSegmentSanitizer.Sanitize(aid)}/{PathSegmentSanitizer.Sanitize(aid)}.{PathSegmentSanitizer.Sanitize(cid)}";
        var usedPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var group in subtitles.GroupBy(subtitle => PathSegmentSanitizer.Sanitize(subtitle.lan), StringComparer.OrdinalIgnoreCase))
        {
            var items = group.ToList();
            for (int i = 0; i < items.Count; i++)
            {
                string extension = Path.GetExtension(items[i].path);
                if (extension is not ".srt" and not ".ass")
                    extension = ".srt";
                string? id = items[i].id;
                string suffix = items.Count == 1 ? "" : "." + (string.IsNullOrEmpty(id) ? (i + 1).ToString() : PathSegmentSanitizer.Sanitize(id));
                string stem = $"{prefix}.{PathSegmentSanitizer.Sanitize(items[i].lan)}{suffix}";
                string path = stem + extension;
                for (int n = 2; !usedPaths.Add(path); n++) path = $"{stem}.{n}{extension}";
                items[i].path = path;
            }
        }
    }

    #endregion

    public static async Task<List<Subtitle>> GetSubtitlesAsync(string aid, string cid, string epId, int index, bool intl)
    {
        if (intl)
        {
            return await GetIntlSubtitlesAsync(aid, cid, epId, index, url => GetSubtitleWebTextAsync(url));
        }

        return await GetDomesticSubtitlesAsync(aid, cid, AppHttpClient);
    }

    internal static async Task<List<Subtitle>> GetIntlSubtitlesAsync(string aid, string cid, string epId, int index, Func<string, Task<string>> fetch)
    {
        var first = await GetIntlSubtitlesFromApi1Async(aid, cid, epId, index, fetch);
        List<List<Subtitle>?> sources = [first];
        if (!HasUsableSubtitle(first)) sources.Add(await GetIntlSubtitlesFromApi2Async(aid, cid, epId, index, fetch));
        return MergeSubtitleSources(sources, aid, cid);
    }

    // Domestic subtitles use the current web endpoint exclusively. Do not fall back
    // to player/view/DM APIs: their metadata and authentication requirements differ.
    internal static async Task<List<Subtitle>> GetDomesticSubtitlesAsync(string aid, string cid, HttpClient client)
    {
        var source = await GetSubtitlesFromWebApiAsync(aid, cid, client);
        var subtitles = MergeSubtitleSources([source], aid, cid);
        if (subtitles.Count == 0)
            LogWarn(source is null ? "新版字幕接口请求失败" : "未找到可用字幕，可能需要登录或该视频没有字幕");
        return subtitles;
    }

    public static async Task SaveSubtitleAsync(string url, string path)
    {
        if (path.EndsWith(".srt"))
            await File.WriteAllTextAsync(path, ConvertSubFromJson(await GetSubtitleWebTextAsync(url)), Encoding.UTF8);
        else
            await File.WriteAllTextAsync(path, await GetSubtitleWebTextAsync(url), Encoding.UTF8);
    }

    private static string ConvertSubFromJson(string jsonString)
    {
        StringBuilder lines = new();
        using var json = JsonDocument.Parse(jsonString);
        var sub = json.RootElement.GetProperty("body").EnumerateArray().ToList();
        for(int i = 0; i < sub.Count; i++)
        {
            var line = sub[i];
            lines.AppendLine((i + 1).ToString());
            if (line.TryGetProperty("from", out JsonElement from))
            {
                lines.AppendLine($"{FormatTime(from.GetDouble())} --> {FormatTime(line.GetProperty("to").GetDouble())}");
            }
            else
            {
                lines.AppendLine($"{FormatTime(0.0)} --> {FormatTime(line.GetProperty("to").GetDouble())}");
            }
            //有的没有内容
            if (line.TryGetProperty("content", out JsonElement content))
                lines.AppendLine(content.ToString());
            lines.AppendLine();
        }
        return lines.ToString();
    }

    private static string FormatTime(double sec) //64.13
    {
        return TimeSpan.FromSeconds(sec).ToString(@"hh\:mm\:ss\,fff");
    }

    [GeneratedRegex("-[a-z]")]
    private static partial Regex NonCapsRegex();
}
